name: Ping

# Schedule every 5 minutes
on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: |
          curl -fsS https://hello-world-x3w9.onrender.com/ping || echo "Ping failed"
